# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\assets\UI\Layout\ConnectorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Connector(object):
    def setupUi(self, Connector):
        Connector.setObjectName("Connector")
        Connector.setWindowModality(QtCore.Qt.ApplicationModal)
        Connector.resize(351, 271)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Connector.sizePolicy().hasHeightForWidth())
        Connector.setSizePolicy(sizePolicy)
        Connector.setMinimumSize(QtCore.QSize(351, 271))
        Connector.setMaximumSize(QtCore.QSize(351, 271))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Connector.setFont(font)
        Connector.setDockNestingEnabled(False)
        Connector.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(Connector)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 331, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.host_in = QtWidgets.QLineEdit(self.groupBox)
        self.host_in.setGeometry(QtCore.QRect(10, 110, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.host_in.setFont(font)
        self.host_in.setFrame(False)
        self.host_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.host_in.setClearButtonEnabled(True)
        self.host_in.setObjectName("host_in")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 28, 310, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("padding:4")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.port_in = QtWidgets.QLineEdit(self.groupBox)
        self.port_in.setGeometry(QtCore.QRect(141, 110, 88, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.port_in.setFont(font)
        self.port_in.setFrame(False)
        self.port_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.port_in.setClearButtonEnabled(True)
        self.port_in.setObjectName("port_in")
        self.user_in = QtWidgets.QLineEdit(self.groupBox)
        self.user_in.setGeometry(QtCore.QRect(10, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.user_in.setFont(font)
        self.user_in.setFrame(False)
        self.user_in.setClearButtonEnabled(True)
        self.user_in.setObjectName("user_in")
        self.buttons = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttons.setGeometry(QtCore.QRect(10, 200, 311, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttons.setFont(font)
        self.buttons.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttons.setStyleSheet("    min-width: 80px;\n"
" min-height: 20px;")
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open)
        self.buttons.setCenterButtons(True)
        self.buttons.setObjectName("buttons")
        self.pass_in = QtWidgets.QLineEdit(self.groupBox)
        self.pass_in.setGeometry(QtCore.QRect(141, 150, 88, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pass_in.setFont(font)
        self.pass_in.setFrame(False)
        self.pass_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.pass_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.pass_in.setClearButtonEnabled(True)
        self.pass_in.setObjectName("pass_in")
        self.trusted = QtWidgets.QCheckBox(self.groupBox)
        self.trusted.setEnabled(False)
        self.trusted.setGeometry(QtCore.QRect(241, 150, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.trusted.setFont(font)
        self.trusted.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.trusted.setCheckable(True)
        self.trusted.setChecked(True)
        self.trusted.setAutoRepeat(False)
        self.trusted.setAutoExclusive(False)
        self.trusted.setTristate(False)
        self.trusted.setObjectName("trusted")
        self.driver_in = QtWidgets.QLineEdit(self.groupBox)
        self.driver_in.setEnabled(False)
        self.driver_in.setGeometry(QtCore.QRect(10, 70, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.driver_in.setFont(font)
        self.driver_in.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.driver_in.setFrame(False)
        self.driver_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.driver_in.setClearButtonEnabled(True)
        self.driver_in.setObjectName("driver_in")
        self.buffered = QtWidgets.QCheckBox(self.groupBox)
        self.buffered.setEnabled(True)
        self.buffered.setGeometry(QtCore.QRect(241, 110, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buffered.setFont(font)
        self.buffered.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buffered.setCheckable(True)
        self.buffered.setChecked(True)
        self.buffered.setAutoRepeat(False)
        self.buffered.setAutoExclusive(False)
        self.buffered.setTristate(False)
        self.buffered.setObjectName("buffered")
        self.driver = QtWidgets.QCheckBox(self.groupBox)
        self.driver.setEnabled(False)
        self.driver.setGeometry(QtCore.QRect(241, 70, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.driver.setFont(font)
        self.driver.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.driver.setCheckable(True)
        self.driver.setChecked(True)
        self.driver.setAutoRepeat(False)
        self.driver.setAutoExclusive(False)
        self.driver.setTristate(False)
        self.driver.setObjectName("driver")
        Connector.setCentralWidget(self.centralwidget)

        self.retranslateUi(Connector)
        QtCore.QMetaObject.connectSlotsByName(Connector)
        Connector.setTabOrder(self.comboBox, self.driver_in)
        Connector.setTabOrder(self.driver_in, self.driver)
        Connector.setTabOrder(self.driver, self.host_in)
        Connector.setTabOrder(self.host_in, self.port_in)
        Connector.setTabOrder(self.port_in, self.buffered)
        Connector.setTabOrder(self.buffered, self.user_in)
        Connector.setTabOrder(self.user_in, self.pass_in)
        Connector.setTabOrder(self.pass_in, self.trusted)

    def retranslateUi(self, Connector):
        _translate = QtCore.QCoreApplication.translate
        Connector.setWindowTitle(_translate("Connector", "SQL Connector"))
        self.groupBox.setTitle(_translate("Connector", "Login"))
        self.host_in.setToolTip(_translate("Connector", "<html><head/><body><p>Server / IP</p></body></html>"))
        self.host_in.setText(_translate("Connector", "127.0.0.1"))
        self.host_in.setPlaceholderText(_translate("Connector", "Server/IP:"))
        self.comboBox.setItemText(0, _translate("Connector", "MYSQL (TCP/IP)"))
        self.comboBox.setItemText(1, _translate("Connector", "Microsoft Server (TCP/IP)"))
        self.comboBox.setItemText(2, _translate("Connector", "Postgre SQL (Experimental)"))
        self.port_in.setToolTip(_translate("Connector", "<html><head/><body><p>Server PORT</p></body></html>"))
        self.port_in.setText(_translate("Connector", "3306"))
        self.port_in.setPlaceholderText(_translate("Connector", "Port:"))
        self.user_in.setToolTip(_translate("Connector", "<html><head/><body><p>Username</p></body></html>"))
        self.user_in.setText(_translate("Connector", "root"))
        self.user_in.setPlaceholderText(_translate("Connector", "User:"))
        self.pass_in.setToolTip(_translate("Connector", "<html><head/><body><p>Password</p></body></html>"))
        self.pass_in.setText(_translate("Connector", "123456"))
        self.pass_in.setPlaceholderText(_translate("Connector", "Password:"))
        self.trusted.setToolTip(_translate("Connector", "<html><head/><body><p>Trusted Connection</p></body></html>"))
        self.trusted.setText(_translate("Connector", "Trusted"))
        self.driver_in.setToolTip(_translate("Connector", "<html><head/><body><p>Driver</p></body></html>"))
        self.driver_in.setText(_translate("Connector", "SQL Server Native Client 11.0"))
        self.driver_in.setPlaceholderText(_translate("Connector", "Driver:"))
        self.buffered.setToolTip(_translate("Connector", "<html><head/><body><p>Buffered Connection</p></body></html>"))
        self.buffered.setText(_translate("Connector", "Buffered"))
        self.driver.setToolTip(_translate("Connector", "<html><head/><body><p>Use server Driver</p></body></html>"))
        self.driver.setText(_translate("Connector", "Use Driver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Connector = QtWidgets.QMainWindow()
    ui = Ui_Connector()
    ui.setupUi(Connector)
    Connector.show()
    sys.exit(app.exec_())

