# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\assets\UI\Layout\DB_Creator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Creator(object):
    def setupUi(self, Creator):
        Creator.setObjectName("Creator")
        Creator.setWindowModality(QtCore.Qt.ApplicationModal)
        Creator.resize(340, 327)
        self.centralwidget = QtWidgets.QWidget(Creator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(90, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dbName = QtWidgets.QLineEdit(self.centralwidget)
        self.dbName.setMinimumSize(QtCore.QSize(220, 30))
        self.dbName.setObjectName("dbName")
        self.gridLayout.addWidget(self.dbName, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(220, 31))
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(91, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.create_dialog = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.create_dialog.setMinimumSize(QtCore.QSize(15, 15))
        self.create_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.create_dialog.setCenterButtons(False)
        self.create_dialog.setObjectName("create_dialog")
        self.gridLayout.addWidget(self.create_dialog, 2, 1, 1, 1)
        self.query_preview = QtWidgets.QTextBrowser(self.centralwidget)
        self.query_preview.setMinimumSize(QtCore.QSize(316, 190))
        self.query_preview.setObjectName("query_preview")
        self.gridLayout.addWidget(self.query_preview, 3, 0, 1, 2)
        Creator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Creator)
        QtCore.QMetaObject.connectSlotsByName(Creator)

    def retranslateUi(self, Creator):
        _translate = QtCore.QCoreApplication.translate
        Creator.setWindowTitle(_translate("Creator", "Database Creator"))
        self.label.setText(_translate("Creator", "Name:"))
        self.dbName.setPlaceholderText(_translate("Creator", "Enter DB Name:"))
        self.label_2.setText(_translate("Creator", "Collation:"))
        self.comboBox.setItemText(0, _translate("Creator", "utf8_bin"))
        self.comboBox.setItemText(1, _translate("Creator", "big5_chinese_ci"))
        self.comboBox.setItemText(2, _translate("Creator", "big5_bin"))
        self.comboBox.setItemText(3, _translate("Creator", "dec8_swedish_ci"))
        self.comboBox.setItemText(4, _translate("Creator", "dec8_bin"))
        self.comboBox.setItemText(5, _translate("Creator", "cp850_general_ci"))
        self.comboBox.setItemText(6, _translate("Creator", "cp850_bin"))
        self.comboBox.setItemText(7, _translate("Creator", "hp8_english_ci"))
        self.comboBox.setItemText(8, _translate("Creator", "hp8_bin"))
        self.comboBox.setItemText(9, _translate("Creator", "koi8r_general_ci"))
        self.comboBox.setItemText(10, _translate("Creator", "koi8r_bin"))
        self.comboBox.setItemText(11, _translate("Creator", "latin1_german1_ci"))
        self.comboBox.setItemText(12, _translate("Creator", "latin1_swedish_ci"))
        self.comboBox.setItemText(13, _translate("Creator", "latin1_danish_ci"))
        self.comboBox.setItemText(14, _translate("Creator", "latin1_german2_ci"))
        self.comboBox.setItemText(15, _translate("Creator", "latin1_bin"))
        self.comboBox.setItemText(16, _translate("Creator", "latin1_general_ci"))
        self.comboBox.setItemText(17, _translate("Creator", "latin1_general_cs"))
        self.comboBox.setItemText(18, _translate("Creator", "latin1_spanish_ci"))
        self.comboBox.setItemText(19, _translate("Creator", "latin2_czech_cs"))
        self.comboBox.setItemText(20, _translate("Creator", "latin2_general_ci"))
        self.comboBox.setItemText(21, _translate("Creator", "latin2_hungarian_ci"))
        self.comboBox.setItemText(22, _translate("Creator", "latin2_croatian_ci"))
        self.comboBox.setItemText(23, _translate("Creator", "latin2_bin"))
        self.comboBox.setItemText(24, _translate("Creator", "swe7_swedish_ci"))
        self.comboBox.setItemText(25, _translate("Creator", "swe7_bin"))
        self.comboBox.setItemText(26, _translate("Creator", "ascii_general_ci"))
        self.comboBox.setItemText(27, _translate("Creator", "ascii_bin"))
        self.comboBox.setItemText(28, _translate("Creator", "ujis_japanese_ci"))
        self.comboBox.setItemText(29, _translate("Creator", "ujis_bin"))
        self.comboBox.setItemText(30, _translate("Creator", "sjis_japanese_ci"))
        self.comboBox.setItemText(31, _translate("Creator", "sjis_bin"))
        self.comboBox.setItemText(32, _translate("Creator", "hebrew_general_ci"))
        self.comboBox.setItemText(33, _translate("Creator", "hebrew_bin"))
        self.comboBox.setItemText(34, _translate("Creator", "tis620_thai_ci"))
        self.comboBox.setItemText(35, _translate("Creator", "tis620_bin"))
        self.comboBox.setItemText(36, _translate("Creator", "euckr_korean_ci"))
        self.comboBox.setItemText(37, _translate("Creator", "euckr_bin"))
        self.comboBox.setItemText(38, _translate("Creator", "koi8u_general_ci"))
        self.comboBox.setItemText(39, _translate("Creator", "koi8u_bin"))
        self.comboBox.setItemText(40, _translate("Creator", "gb2312_chinese_ci"))
        self.comboBox.setItemText(41, _translate("Creator", "gb2312_bin"))
        self.comboBox.setItemText(42, _translate("Creator", "greek_general_ci"))
        self.comboBox.setItemText(43, _translate("Creator", "greek_bin"))
        self.comboBox.setItemText(44, _translate("Creator", "cp1250_general_ci"))
        self.comboBox.setItemText(45, _translate("Creator", "cp1250_czech_cs"))
        self.comboBox.setItemText(46, _translate("Creator", "cp1250_croatian_ci"))
        self.comboBox.setItemText(47, _translate("Creator", "cp1250_bin"))
        self.comboBox.setItemText(48, _translate("Creator", "cp1250_polish_ci"))
        self.comboBox.setItemText(49, _translate("Creator", "gbk_chinese_ci"))
        self.comboBox.setItemText(50, _translate("Creator", "gbk_bin"))
        self.comboBox.setItemText(51, _translate("Creator", "latin5_turkish_ci"))
        self.comboBox.setItemText(52, _translate("Creator", "latin5_bin"))
        self.comboBox.setItemText(53, _translate("Creator", "armscii8_general_ci"))
        self.comboBox.setItemText(54, _translate("Creator", "armscii8_bin"))
        self.comboBox.setItemText(55, _translate("Creator", "utf8_general_ci"))
        self.comboBox.setItemText(56, _translate("Creator", "utf8_unicode_ci"))
        self.comboBox.setItemText(57, _translate("Creator", "utf8_icelandic_ci"))
        self.comboBox.setItemText(58, _translate("Creator", "utf8_latvian_ci"))
        self.comboBox.setItemText(59, _translate("Creator", "utf8_romanian_ci"))
        self.comboBox.setItemText(60, _translate("Creator", "utf8_slovenian_ci"))
        self.comboBox.setItemText(61, _translate("Creator", "utf8_polish_ci"))
        self.comboBox.setItemText(62, _translate("Creator", "utf8_estonian_ci"))
        self.comboBox.setItemText(63, _translate("Creator", "utf8_spanish_ci"))
        self.comboBox.setItemText(64, _translate("Creator", "utf8_swedish_ci"))
        self.comboBox.setItemText(65, _translate("Creator", "utf8_turkish_ci"))
        self.comboBox.setItemText(66, _translate("Creator", "utf8_czech_ci"))
        self.comboBox.setItemText(67, _translate("Creator", "utf8_danish_ci"))
        self.comboBox.setItemText(68, _translate("Creator", "utf8_lithuanian_ci"))
        self.comboBox.setItemText(69, _translate("Creator", "utf8_slovak_ci"))
        self.comboBox.setItemText(70, _translate("Creator", "utf8_spanish2_ci"))
        self.comboBox.setItemText(71, _translate("Creator", "utf8_roman_ci"))
        self.comboBox.setItemText(72, _translate("Creator", "utf8_persian_ci"))
        self.comboBox.setItemText(73, _translate("Creator", "utf8_esperanto_ci"))
        self.comboBox.setItemText(74, _translate("Creator", "utf8_hungarian_ci"))
        self.comboBox.setItemText(75, _translate("Creator", "utf8_sinhala_ci"))
        self.comboBox.setItemText(76, _translate("Creator", "utf8_german2_ci"))
        self.comboBox.setItemText(77, _translate("Creator", "utf8_croatian_ci"))
        self.comboBox.setItemText(78, _translate("Creator", "utf8_unicode_520_ci"))
        self.comboBox.setItemText(79, _translate("Creator", "utf8_vietnamese_ci"))
        self.comboBox.setItemText(80, _translate("Creator", "utf8_general_mysql500_ci"))
        self.comboBox.setItemText(81, _translate("Creator", "ucs2_general_ci"))
        self.comboBox.setItemText(82, _translate("Creator", "ucs2_bin"))
        self.comboBox.setItemText(83, _translate("Creator", "ucs2_unicode_ci"))
        self.comboBox.setItemText(84, _translate("Creator", "ucs2_icelandic_ci"))
        self.comboBox.setItemText(85, _translate("Creator", "ucs2_latvian_ci"))
        self.comboBox.setItemText(86, _translate("Creator", "ucs2_romanian_ci"))
        self.comboBox.setItemText(87, _translate("Creator", "ucs2_slovenian_ci"))
        self.comboBox.setItemText(88, _translate("Creator", "ucs2_polish_ci"))
        self.comboBox.setItemText(89, _translate("Creator", "ucs2_estonian_ci"))
        self.comboBox.setItemText(90, _translate("Creator", "ucs2_spanish_ci"))
        self.comboBox.setItemText(91, _translate("Creator", "ucs2_swedish_ci"))
        self.comboBox.setItemText(92, _translate("Creator", "ucs2_turkish_ci"))
        self.comboBox.setItemText(93, _translate("Creator", "ucs2_czech_ci"))
        self.comboBox.setItemText(94, _translate("Creator", "ucs2_danish_ci"))
        self.comboBox.setItemText(95, _translate("Creator", "ucs2_lithuanian_ci"))
        self.comboBox.setItemText(96, _translate("Creator", "ucs2_slovak_ci"))
        self.comboBox.setItemText(97, _translate("Creator", "ucs2_spanish2_ci"))
        self.comboBox.setItemText(98, _translate("Creator", "ucs2_roman_ci"))
        self.comboBox.setItemText(99, _translate("Creator", "ucs2_persian_ci"))
        self.comboBox.setItemText(100, _translate("Creator", "ucs2_esperanto_ci"))
        self.comboBox.setItemText(101, _translate("Creator", "ucs2_hungarian_ci"))
        self.comboBox.setItemText(102, _translate("Creator", "ucs2_sinhala_ci"))
        self.comboBox.setItemText(103, _translate("Creator", "ucs2_german2_ci"))
        self.comboBox.setItemText(104, _translate("Creator", "ucs2_croatian_ci"))
        self.comboBox.setItemText(105, _translate("Creator", "ucs2_unicode_520_ci"))
        self.comboBox.setItemText(106, _translate("Creator", "ucs2_vietnamese_ci"))
        self.comboBox.setItemText(107, _translate("Creator", "ucs2_general_mysql500_ci"))
        self.comboBox.setItemText(108, _translate("Creator", "cp866_general_ci"))
        self.comboBox.setItemText(109, _translate("Creator", "cp866_bin"))
        self.comboBox.setItemText(110, _translate("Creator", "keybcs2_general_ci"))
        self.comboBox.setItemText(111, _translate("Creator", "keybcs2_bin"))
        self.comboBox.setItemText(112, _translate("Creator", "macce_general_ci"))
        self.comboBox.setItemText(113, _translate("Creator", "macce_bin"))
        self.comboBox.setItemText(114, _translate("Creator", "macroman_general_ci"))
        self.comboBox.setItemText(115, _translate("Creator", "macroman_bin"))
        self.comboBox.setItemText(116, _translate("Creator", "cp852_general_ci"))
        self.comboBox.setItemText(117, _translate("Creator", "cp852_bin"))
        self.comboBox.setItemText(118, _translate("Creator", "latin7_estonian_cs"))
        self.comboBox.setItemText(119, _translate("Creator", "latin7_general_ci"))
        self.comboBox.setItemText(120, _translate("Creator", "latin7_general_cs"))
        self.comboBox.setItemText(121, _translate("Creator", "latin7_bin"))
        self.comboBox.setItemText(122, _translate("Creator", "utf8mb4_general_ci"))
        self.comboBox.setItemText(123, _translate("Creator", "utf8mb4_bin"))
        self.comboBox.setItemText(124, _translate("Creator", "utf8mb4_unicode_ci"))
        self.comboBox.setItemText(125, _translate("Creator", "utf8mb4_icelandic_ci"))
        self.comboBox.setItemText(126, _translate("Creator", "utf8mb4_latvian_ci"))
        self.comboBox.setItemText(127, _translate("Creator", "utf8mb4_romanian_ci"))
        self.comboBox.setItemText(128, _translate("Creator", "utf8mb4_slovenian_ci"))
        self.comboBox.setItemText(129, _translate("Creator", "utf8mb4_polish_ci"))
        self.comboBox.setItemText(130, _translate("Creator", "utf8mb4_estonian_ci"))
        self.comboBox.setItemText(131, _translate("Creator", "utf8mb4_spanish_ci"))
        self.comboBox.setItemText(132, _translate("Creator", "utf8mb4_swedish_ci"))
        self.comboBox.setItemText(133, _translate("Creator", "utf8mb4_turkish_ci"))
        self.comboBox.setItemText(134, _translate("Creator", "utf8mb4_czech_ci"))
        self.comboBox.setItemText(135, _translate("Creator", "utf8mb4_danish_ci"))
        self.comboBox.setItemText(136, _translate("Creator", "utf8mb4_lithuanian_ci"))
        self.comboBox.setItemText(137, _translate("Creator", "utf8mb4_slovak_ci"))
        self.comboBox.setItemText(138, _translate("Creator", "utf8mb4_spanish2_ci"))
        self.comboBox.setItemText(139, _translate("Creator", "utf8mb4_roman_ci"))
        self.comboBox.setItemText(140, _translate("Creator", "utf8mb4_persian_ci"))
        self.comboBox.setItemText(141, _translate("Creator", "utf8mb4_esperanto_ci"))
        self.comboBox.setItemText(142, _translate("Creator", "utf8mb4_hungarian_ci"))
        self.comboBox.setItemText(143, _translate("Creator", "utf8mb4_sinhala_ci"))
        self.comboBox.setItemText(144, _translate("Creator", "utf8mb4_german2_ci"))
        self.comboBox.setItemText(145, _translate("Creator", "utf8mb4_croatian_ci"))
        self.comboBox.setItemText(146, _translate("Creator", "utf8mb4_unicode_520_ci"))
        self.comboBox.setItemText(147, _translate("Creator", "utf8mb4_vietnamese_ci"))
        self.comboBox.setItemText(148, _translate("Creator", "cp1251_bulgarian_ci"))
        self.comboBox.setItemText(149, _translate("Creator", "cp1251_ukrainian_ci"))
        self.comboBox.setItemText(150, _translate("Creator", "cp1251_bin"))
        self.comboBox.setItemText(151, _translate("Creator", "cp1251_general_ci"))
        self.comboBox.setItemText(152, _translate("Creator", "cp1251_general_cs"))
        self.comboBox.setItemText(153, _translate("Creator", "utf16_general_ci"))
        self.comboBox.setItemText(154, _translate("Creator", "utf16_bin"))
        self.comboBox.setItemText(155, _translate("Creator", "utf16_unicode_ci"))
        self.comboBox.setItemText(156, _translate("Creator", "utf16_icelandic_ci"))
        self.comboBox.setItemText(157, _translate("Creator", "utf16_latvian_ci"))
        self.comboBox.setItemText(158, _translate("Creator", "utf16_romanian_ci"))
        self.comboBox.setItemText(159, _translate("Creator", "utf16_slovenian_ci"))
        self.comboBox.setItemText(160, _translate("Creator", "utf16_polish_ci"))
        self.comboBox.setItemText(161, _translate("Creator", "utf16_estonian_ci"))
        self.comboBox.setItemText(162, _translate("Creator", "utf16_spanish_ci"))
        self.comboBox.setItemText(163, _translate("Creator", "utf16_swedish_ci"))
        self.comboBox.setItemText(164, _translate("Creator", "utf16_turkish_ci"))
        self.comboBox.setItemText(165, _translate("Creator", "utf16_czech_ci"))
        self.comboBox.setItemText(166, _translate("Creator", "utf16_danish_ci"))
        self.comboBox.setItemText(167, _translate("Creator", "utf16_lithuanian_ci"))
        self.comboBox.setItemText(168, _translate("Creator", "utf16_slovak_ci"))
        self.comboBox.setItemText(169, _translate("Creator", "utf16_spanish2_ci"))
        self.comboBox.setItemText(170, _translate("Creator", "utf16_roman_ci"))
        self.comboBox.setItemText(171, _translate("Creator", "utf16_persian_ci"))
        self.comboBox.setItemText(172, _translate("Creator", "utf16_esperanto_ci"))
        self.comboBox.setItemText(173, _translate("Creator", "utf16_hungarian_ci"))
        self.comboBox.setItemText(174, _translate("Creator", "utf16_sinhala_ci"))
        self.comboBox.setItemText(175, _translate("Creator", "utf16_german2_ci"))
        self.comboBox.setItemText(176, _translate("Creator", "utf16_croatian_ci"))
        self.comboBox.setItemText(177, _translate("Creator", "utf16_unicode_520_ci"))
        self.comboBox.setItemText(178, _translate("Creator", "utf16_vietnamese_ci"))
        self.comboBox.setItemText(179, _translate("Creator", "utf16le_general_ci"))
        self.comboBox.setItemText(180, _translate("Creator", "utf16le_bin"))
        self.comboBox.setItemText(181, _translate("Creator", "cp1256_general_ci"))
        self.comboBox.setItemText(182, _translate("Creator", "cp1256_bin"))
        self.comboBox.setItemText(183, _translate("Creator", "cp1257_lithuanian_ci"))
        self.comboBox.setItemText(184, _translate("Creator", "cp1257_bin"))
        self.comboBox.setItemText(185, _translate("Creator", "cp1257_general_ci"))
        self.comboBox.setItemText(186, _translate("Creator", "utf32_general_ci"))
        self.comboBox.setItemText(187, _translate("Creator", "utf32_bin"))
        self.comboBox.setItemText(188, _translate("Creator", "utf32_unicode_ci"))
        self.comboBox.setItemText(189, _translate("Creator", "utf32_icelandic_ci"))
        self.comboBox.setItemText(190, _translate("Creator", "utf32_latvian_ci"))
        self.comboBox.setItemText(191, _translate("Creator", "utf32_romanian_ci"))
        self.comboBox.setItemText(192, _translate("Creator", "utf32_slovenian_ci"))
        self.comboBox.setItemText(193, _translate("Creator", "utf32_polish_ci"))
        self.comboBox.setItemText(194, _translate("Creator", "utf32_estonian_ci"))
        self.comboBox.setItemText(195, _translate("Creator", "utf32_spanish_ci"))
        self.comboBox.setItemText(196, _translate("Creator", "utf32_swedish_ci"))
        self.comboBox.setItemText(197, _translate("Creator", "utf32_turkish_ci"))
        self.comboBox.setItemText(198, _translate("Creator", "utf32_czech_ci"))
        self.comboBox.setItemText(199, _translate("Creator", "utf32_danish_ci"))
        self.comboBox.setItemText(200, _translate("Creator", "utf32_lithuanian_ci"))
        self.comboBox.setItemText(201, _translate("Creator", "utf32_slovak_ci"))
        self.comboBox.setItemText(202, _translate("Creator", "utf32_spanish2_ci"))
        self.comboBox.setItemText(203, _translate("Creator", "utf32_roman_ci"))
        self.comboBox.setItemText(204, _translate("Creator", "utf32_persian_ci"))
        self.comboBox.setItemText(205, _translate("Creator", "utf32_esperanto_ci"))
        self.comboBox.setItemText(206, _translate("Creator", "utf32_hungarian_ci"))
        self.comboBox.setItemText(207, _translate("Creator", "utf32_sinhala_ci"))
        self.comboBox.setItemText(208, _translate("Creator", "utf32_german2_ci"))
        self.comboBox.setItemText(209, _translate("Creator", "utf32_croatian_ci"))
        self.comboBox.setItemText(210, _translate("Creator", "utf32_unicode_520_ci"))
        self.comboBox.setItemText(211, _translate("Creator", "utf32_vietnamese_ci"))
        self.comboBox.setItemText(212, _translate("Creator", "binary"))
        self.comboBox.setItemText(213, _translate("Creator", "geostd8_general_ci"))
        self.comboBox.setItemText(214, _translate("Creator", "geostd8_bin"))
        self.comboBox.setItemText(215, _translate("Creator", "cp932_japanese_ci"))
        self.comboBox.setItemText(216, _translate("Creator", "cp932_bin"))
        self.comboBox.setItemText(217, _translate("Creator", "eucjpms_japanese_ci"))
        self.comboBox.setItemText(218, _translate("Creator", "eucjpms_bin"))
        self.label_3.setText(_translate("Creator", "Create code:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Creator = QtWidgets.QMainWindow()
    ui = Ui_Creator()
    ui.setupUi(Creator)
    Creator.show()
    sys.exit(app.exec_())

