# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\assets\UI\Layout\DB_Creator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Creator(object):
    def setupUi(self, Creator):
        Creator.setObjectName("Creator")
        Creator.resize(873, 602)
        Creator.setMinimumSize(QtCore.QSize(644, 602))
        self.centralwidget = QtWidgets.QWidget(Creator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(330, 480))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 13, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(280, 30))
        self.label_2.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        self.d_name = QtWidgets.QLineEdit(self.centralwidget)
        self.d_name.setMinimumSize(QtCore.QSize(281, 30))
        self.d_name.setMaximumSize(QtCore.QSize(290, 30))
        self.d_name.setObjectName("d_name")
        self.gridLayout.addWidget(self.d_name, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(280, 30))
        self.label.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 2)
        self.f_name = QtWidgets.QLineEdit(self.centralwidget)
        self.f_name.setMinimumSize(QtCore.QSize(280, 30))
        self.f_name.setMaximumSize(QtCore.QSize(290, 30))
        self.f_name.setObjectName("f_name")
        self.gridLayout.addWidget(self.f_name, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(160, 30))
        self.label_3.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(124, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(160, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(160, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 5, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(110, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(124, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(290, 126))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 270, 30))
        self.checkBox.setMaximumSize(QtCore.QSize(270, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(25, 25))
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 270, 30))
        self.checkBox_2.setMaximumSize(QtCore.QSize(270, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setIconSize(QtCore.QSize(25, 25))
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 80, 270, 30))
        self.checkBox_3.setMaximumSize(QtCore.QSize(270, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setIconSize(QtCore.QSize(25, 25))
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.groupBox, 6, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(280, 20))
        self.label_5.setMaximumSize(QtCore.QSize(280, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(280, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(290, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 8, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(280, 20))
        self.label_6.setMaximumSize(QtCore.QSize(280, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 1, 1, 2)
        self.f_name_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.f_name_2.setMinimumSize(QtCore.QSize(280, 30))
        self.f_name_2.setMaximumSize(QtCore.QSize(290, 30))
        self.f_name_2.setObjectName("f_name_2")
        self.gridLayout.addWidget(self.f_name_2, 10, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(280, 20))
        self.label_7.setMaximumSize(QtCore.QSize(280, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 1, 1, 2)
        self.f_name_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.f_name_3.setMinimumSize(QtCore.QSize(280, 30))
        self.f_name_3.setMaximumSize(QtCore.QSize(290, 30))
        self.f_name_3.setObjectName("f_name_3")
        self.gridLayout.addWidget(self.f_name_3, 12, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(330, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 13, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(280, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(290, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 13, 1, 1, 2, QtCore.Qt.AlignVCenter)
        self.groupBox.raise_()
        self.d_name.raise_()
        self.f_name.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.comboBox_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.f_name_2.raise_()
        self.f_name_3.raise_()
        self.label_7.raise_()
        self.plainTextEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        Creator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Creator)
        QtCore.QMetaObject.connectSlotsByName(Creator)

    def retranslateUi(self, Creator):
        _translate = QtCore.QCoreApplication.translate
        Creator.setWindowTitle(_translate("Creator", "MainWindow"))
        self.label_2.setText(_translate("Creator", "Table name:"))
        self.label.setText(_translate("Creator", "Field name:"))
        self.label_3.setText(_translate("Creator", "Tipo de dados:"))
        self.label_4.setText(_translate("Creator", "Valor:"))
        self.comboBox.setItemText(0, _translate("Creator", "TINYINT"))
        self.comboBox.setItemText(1, _translate("Creator", "SMALLINT"))
        self.comboBox.setItemText(2, _translate("Creator", "MEDIUMINT"))
        self.comboBox.setItemText(3, _translate("Creator", "INT"))
        self.comboBox.setItemText(4, _translate("Creator", "BIGINT"))
        self.comboBox.setItemText(5, _translate("Creator", "BIT"))
        self.comboBox.setItemText(6, _translate("Creator", "FLOAT"))
        self.comboBox.setItemText(7, _translate("Creator", "DOUBLE"))
        self.comboBox.setItemText(8, _translate("Creator", "DECIMAL"))
        self.comboBox.setItemText(9, _translate("Creator", "CHAR"))
        self.comboBox.setItemText(10, _translate("Creator", "VARCHAR"))
        self.comboBox.setItemText(11, _translate("Creator", "TINYTEXT"))
        self.comboBox.setItemText(12, _translate("Creator", "MEDIUMTEXT"))
        self.comboBox.setItemText(13, _translate("Creator", "LONGTEXT"))
        self.comboBox.setItemText(14, _translate("Creator", "JSON"))
        self.comboBox.setItemText(15, _translate("Creator", "BINARY"))
        self.comboBox.setItemText(16, _translate("Creator", "VARBINARY"))
        self.comboBox.setItemText(17, _translate("Creator", "BLOB"))
        self.comboBox.setItemText(18, _translate("Creator", "MEDIUMBLOB"))
        self.comboBox.setItemText(19, _translate("Creator", "LONGBLOB"))
        self.comboBox.setItemText(20, _translate("Creator", "DATE"))
        self.comboBox.setItemText(21, _translate("Creator", "TIME"))
        self.comboBox.setItemText(22, _translate("Creator", "YEAR"))
        self.comboBox.setItemText(23, _translate("Creator", "DATETIME"))
        self.comboBox.setItemText(24, _translate("Creator", "TIMESTAMP"))
        self.comboBox.setItemText(25, _translate("Creator", "POINT"))
        self.comboBox.setItemText(26, _translate("Creator", "LINESTRING"))
        self.comboBox.setItemText(27, _translate("Creator", "POLYGON"))
        self.comboBox.setItemText(28, _translate("Creator", "GEOMETRY"))
        self.comboBox.setItemText(29, _translate("Creator", "MULTIPOINT"))
        self.comboBox.setItemText(30, _translate("Creator", "MULTILINESTRING"))
        self.comboBox.setItemText(31, _translate("Creator", "MULTIPOLYGON"))
        self.comboBox.setItemText(32, _translate("Creator", "GEOMETRYCOLLECTION"))
        self.comboBox.setItemText(33, _translate("Creator", "ENUM"))
        self.comboBox.setItemText(34, _translate("Creator", "SET"))
        self.groupBox.setTitle(_translate("Creator", "Booleans"))
        self.checkBox.setText(_translate("Creator", "Unsigned"))
        self.checkBox_2.setText(_translate("Creator", "Permitir NULL"))
        self.checkBox_3.setText(_translate("Creator", "ZEROFILL"))
        self.label_5.setText(_translate("Creator", "Padrão:"))
        self.comboBox_2.setItemText(0, _translate("Creator", "N/A"))
        self.comboBox_2.setItemText(1, _translate("Creator", "NULL"))
        self.comboBox_2.setItemText(2, _translate("Creator", "AUTO_INCREMENT"))
        self.label_6.setText(_translate("Creator", "Comment:"))
        self.label_7.setText(_translate("Creator", "Collection"))
        self.f_name_3.setText(_translate("Creator", "utf8_general_ci"))
        self.pushButton_2.setText(_translate("Creator", "EXECUTE CREATE CODE"))
        self.pushButton_2.setShortcut(_translate("Creator", "F9"))
        self.pushButton.setText(_translate("Creator", "REFRESH"))
        self.pushButton.setShortcut(_translate("Creator", "F5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Creator = QtWidgets.QMainWindow()
    ui = Ui_Creator()
    ui.setupUi(Creator)
    Creator.show()
    sys.exit(app.exec_())

