# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\assets\UI\Layout\ConnectorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Connector(object):
    def setupUi(self, Connector):
        Connector.setObjectName("Connector")
        Connector.setWindowModality(QtCore.Qt.ApplicationModal)
        Connector.resize(299, 308)
        Connector.setMaximumSize(QtCore.QSize(299, 308))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Connector.setFont(font)
        Connector.setStyleSheet("")
        Connector.setIconSize(QtCore.QSize(32, 32))
        Connector.setDockNestingEnabled(False)
        Connector.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(Connector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(9, 9, 281, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(101, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxCount(3)
        self.comboBox.setIconSize(QtCore.QSize(32, 32))
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.remember = QtWidgets.QCheckBox(self.centralwidget)
        self.remember.setEnabled(True)
        self.remember.setGeometry(QtCore.QRect(149, 200, 140, 40))
        self.remember.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.remember.setFont(font)
        self.remember.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember.setAutoFillBackground(False)
        self.remember.setStyleSheet("padding:10;background:white;")
        self.remember.setIconSize(QtCore.QSize(32, 32))
        self.remember.setCheckable(True)
        self.remember.setChecked(True)
        self.remember.setAutoRepeat(False)
        self.remember.setAutoExclusive(False)
        self.remember.setTristate(False)
        self.remember.setObjectName("remember")
        self.pass_in = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_in.setGeometry(QtCore.QRect(9, 149, 281, 41))
        self.pass_in.setMinimumSize(QtCore.QSize(281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pass_in.setFont(font)
        self.pass_in.setStyleSheet("padding:7;")
        self.pass_in.setText("")
        self.pass_in.setFrame(False)
        self.pass_in.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.pass_in.setClearButtonEnabled(False)
        self.pass_in.setObjectName("pass_in")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(9, 250, 281, 51))
        self.connect.setMinimumSize(QtCore.QSize(281, 51))
        self.connect.setMaximumSize(QtCore.QSize(281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.connect.setFont(font)
        self.connect.setDefault(True)
        self.connect.setFlat(False)
        self.connect.setObjectName("connect")
        self.user_in = QtWidgets.QLineEdit(self.centralwidget)
        self.user_in.setGeometry(QtCore.QRect(9, 102, 281, 41))
        self.user_in.setMinimumSize(QtCore.QSize(281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.user_in.setFont(font)
        self.user_in.setStyleSheet("padding:7;")
        self.user_in.setText("")
        self.user_in.setFrame(False)
        self.user_in.setClearButtonEnabled(False)
        self.user_in.setObjectName("user_in")
        self.buffered = QtWidgets.QCheckBox(self.centralwidget)
        self.buffered.setEnabled(True)
        self.buffered.setGeometry(QtCore.QRect(9, 200, 130, 40))
        self.buffered.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buffered.setFont(font)
        self.buffered.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buffered.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buffered.setAutoFillBackground(False)
        self.buffered.setStyleSheet("padding:10;background:white;")
        self.buffered.setIconSize(QtCore.QSize(32, 32))
        self.buffered.setCheckable(True)
        self.buffered.setChecked(True)
        self.buffered.setAutoRepeat(False)
        self.buffered.setAutoExclusive(False)
        self.buffered.setTristate(False)
        self.buffered.setObjectName("buffered")
        self.host_in = QtWidgets.QLineEdit(self.centralwidget)
        self.host_in.setGeometry(QtCore.QRect(9, 55, 134, 41))
        self.host_in.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.host_in.setFont(font)
        self.host_in.setStyleSheet("padding:7;")
        self.host_in.setFrame(False)
        self.host_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.host_in.setClearButtonEnabled(False)
        self.host_in.setObjectName("host_in")
        self.port_in = QtWidgets.QLineEdit(self.centralwidget)
        self.port_in.setGeometry(QtCore.QRect(149, 55, 141, 41))
        self.port_in.setMinimumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.port_in.setFont(font)
        self.port_in.setStyleSheet("padding:7;")
        self.port_in.setText("")
        self.port_in.setFrame(False)
        self.port_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.port_in.setClearButtonEnabled(False)
        self.port_in.setObjectName("port_in")
        Connector.setCentralWidget(self.centralwidget)

        self.retranslateUi(Connector)
        QtCore.QMetaObject.connectSlotsByName(Connector)
        Connector.setTabOrder(self.comboBox, self.buffered)
        Connector.setTabOrder(self.buffered, self.host_in)
        Connector.setTabOrder(self.host_in, self.port_in)
        Connector.setTabOrder(self.port_in, self.user_in)
        Connector.setTabOrder(self.user_in, self.pass_in)
        Connector.setTabOrder(self.pass_in, self.remember)

    def retranslateUi(self, Connector):
        _translate = QtCore.QCoreApplication.translate
        Connector.setWindowTitle(_translate("Connector", "SQL Connector"))
        self.comboBox.setItemText(0, _translate("Connector", "MY SQL"))
        self.comboBox.setItemText(1, _translate("Connector", "Microsoft Server"))
        self.comboBox.setItemText(2, _translate("Connector", "Postgre SQL "))
        self.remember.setToolTip(_translate("Connector", "<html><head/><body><p>Trusted Connection</p></body></html>"))
        self.remember.setText(_translate("Connector", "Remember me"))
        self.pass_in.setToolTip(_translate("Connector", "<html><head/><body><p>Password</p></body></html>"))
        self.pass_in.setPlaceholderText(_translate("Connector", "Password:"))
        self.connect.setText(_translate("Connector", "CONNECT"))
        self.user_in.setToolTip(_translate("Connector", "<html><head/><body><p>Username</p></body></html>"))
        self.user_in.setPlaceholderText(_translate("Connector", "User:"))
        self.buffered.setToolTip(_translate("Connector", "<html><head/><body><p>Buffered Connection</p></body></html>"))
        self.buffered.setText(_translate("Connector", "Buffered"))
        self.host_in.setToolTip(_translate("Connector", "<html><head/><body><p>Server / IP</p></body></html>"))
        self.host_in.setText(_translate("Connector", "localhost"))
        self.host_in.setPlaceholderText(_translate("Connector", "Server/IP:"))
        self.port_in.setToolTip(_translate("Connector", "<html><head/><body><p>Server PORT</p></body></html>"))
        self.port_in.setPlaceholderText(_translate("Connector", "Port:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Connector = QtWidgets.QMainWindow()
    ui = Ui_Connector()
    ui.setupUi(Connector)
    Connector.show()
    sys.exit(app.exec_())

